export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as PostPage } from './PostPage'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Root } from './Root'
export { default as NewPost } from './NewPost'
